const ACTIONS = {
  PARTICIPANTS_ADD: 'PARTICIPANTS/ADD',
  PARTICIPANTS_REMOVE: 'PARTICIPANTS/REMOVE',
  PARTICIPANTS_RANDOMIZE: 'PARTICIPANTS/RANDOMIZE',
  PARTICIPANTS_NEXT: 'PARTICIPANTS/NEXT'
}

export default ACTIONS
